name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Test
      id: run-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run Test
        setup-command: pip install -r requirements.txt
        command: pytest
        timeout: 10
        max-score: 20
    - name: pt
      id: pt
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: pip install -r requirments.txt
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-TEST_RESULTS: "${{steps.run-test.outputs.result}}"
        PT_RESULTS: "${{steps.pt.outputs.result}}"
      with:
        runners: run-test,pt
